package mitrais.model;
// Generated Sep 1, 2019 6:25:34 PM by Hibernate Tools 4.3.1



/**
 * Jnskelamin generated by hbm2java
 */
public class Jnskelamin  implements java.io.Serializable {


     private int idkelamin;
     private String jnskelamin;

    public Jnskelamin() {
    }

	
    public Jnskelamin(int idkelamin) {
        this.idkelamin = idkelamin;
    }
    public Jnskelamin(int idkelamin, String jnskelamin) {
       this.idkelamin = idkelamin;
       this.jnskelamin = jnskelamin;
    }
   
    public int getIdkelamin() {
        return this.idkelamin;
    }
    
    public void setIdkelamin(int idkelamin) {
        this.idkelamin = idkelamin;
    }
    public String getJnskelamin() {
        return this.jnskelamin;
    }
    
    public void setJnskelamin(String jnskelamin) {
        this.jnskelamin = jnskelamin;
    }




}


